// Province translation utility for StudentProvince enum to Mongolian names
export const mapProvinceToMongolian = (province: string): string => {
  const provinceTranslations: Record<string, string> = {
    ARKHANGAI: "Архангай",
    BAYAN_ULGII: "Баян-Өлгий",
    BAGANUUR: "Багануур",
    BAGAHANGAI: "Баганхангай",
    BAYANGOL: "Баянхонгор",
    BAYANZURKH: "Баянзүрх",
    BAYANKHONGOR: "Баянхонгор",
    BULGAN: "Булган",
    GOVI_ALTAI: "Говь-Алтай",
    GOVISUMBER: "Говьсүмбэр",
    DARHAN_UUL: "Дархан-Уул",
    DORNOD: "Дорнод",
    DORNOGOVI: "Дорноговь",
    DUNDOGVI: "Дундговь",
    ZAVKHAN: "Завхан",
    ORKHON: "Орхон",
    UVURKHANGAI: "Өвөрхангай",
    UMNUGOVI: "Өмнөговь",
    NALAIKH: "Налайх",
    SONGINOKHAIRKHAN: "Сонгинохайрхан",
    SUKHBAATAR_DUUREG: "Сүхбаатар дүүрэг",
    SUKHBAATAR: "Сүхбаатар",
    SELENGE: "Сэлэнгэ",
    TUV: "Төв",
    UVS: "Увс",
    KHOVD: "Ховд",
    KHAN_UUL: "Хан-Уул",
    KHUVSGUL: "Хөвсгөл",
    KHENTI: "Хэнтий",
    CHINGELTEI: "Чингэлтэй",
  };

  return provinceTranslations[province] || province;
};

// Get all province options for dropdown
export const getAllProvinceOptions = () => {
  return [
    { value: "Бүх аймаг болон дүүрэг", label: "Бүх аймаг болон дүүрэг" },
    { value: "ARKHANGAI", label: "Архангай" },
    { value: "BAYAN_ULGII", label: "Баян-Өлгий" },
    { value: "BAGANUUR", label: "Багануур" },
    { value: "BAGAHANGAI", label: "Баганхангай" },
    { value: "BAYANGOL", label: "Баянхонгор" },
    { value: "BAYANZURKH", label: "Баянзүрх" },
    { value: "BAYANKHONGOR", label: "Баянхонгор" },
    { value: "BULGAN", label: "Булган" },
    { value: "GOVI_ALTAI", label: "Говь-Алтай" },
    { value: "GOVISUMBER", label: "Говьсүмбэр" },
    { value: "DARHAN_UUL", label: "Дархан-Уул" },
    { value: "DORNOD", label: "Дорнод" },
    { value: "DORNOGOVI", label: "Дорноговь" },
    { value: "DUNDOGVI", label: "Дундговь" },
    { value: "ZAVKHAN", label: "Завхан" },
    { value: "ORKHON", label: "Орхон" },
    { value: "UVURKHANGAI", label: "Өвөрхангай" },
    { value: "UMNUGOVI", label: "Өмнөговь" },
    { value: "NALAIKH", label: "Налайх" },
    { value: "SONGINOKHAIRKHAN", label: "Сонгинохайрхан" },
    { value: "SUKHBAATAR_DUUREG", label: "Сүхбаатар дүүрэг" },
    { value: "SUKHBAATAR", label: "Сүхбаатар" },
    { value: "SELENGE", label: "Сэлэнгэ" },
    { value: "TUV", label: "Төв" },
    { value: "UVS", label: "Увс" },
    { value: "KHOVD", label: "Ховд" },
    { value: "KHAN_UUL", label: "Хан-Уул" },
    { value: "KHUVSGUL", label: "Хөвсгөл" },
    { value: "KHENTI", label: "Хэнтий" },
    { value: "CHINGELTEI", label: "Чингэлтэй" },
  ];
};
